apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: codereviewer

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service
        image: thanusri22/auth-service:v2
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: coderaptor-config

        - secretRef:
            name: kv-secret
            optional: true

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kv-secret
              key: DATABASE_URL
              optional: true
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: kv-secret
              key: JWT_SECRET
              optional: true

        ports:
        - containerPort: 8001

        resources:
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: codereviewer
spec:
  selector:
    app: auth-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
