apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: codereviewer

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service
        image: thanusriacr.azurecr.io/auth-service:v1
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: coderaptor-config

        - secretRef:
            name: kv-secret

        ports:
        - containerPort: 8001

        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "kv-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: codereviewer
spec:
  selector:
    app: auth-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
