apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: codereviewer

spec:
  provider: azure

  secretObjects:
  - secretName: kv-secret
    type: Opaque
    data:
    - objectName: AZURE_OPENAI_API_KEY
      key: AZURE_OPENAI_API_KEY

    - objectName: DATABASE_URL
      key: DATABASE_URL

    - objectName: JWT_SECRET
      key: JWT_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e9be58bc-a172-4aa0-8780-ca608a8e16f9"
    keyvaultName: kv-thanusri
    tenantId: cf4a245a-3bc5-4786-be95-383d6c394cf9

    objects: |
      array:
        - |
          objectName: AZUREOPENAIAPIKEY
          objectType: secret
          objectAlias: AZURE_OPENAI_API_KEY
        - |
          objectName: DATABASEURL
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: JWT
          objectType: secret
          objectAlias: JWT_SECRET
