apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: codereviewer

spec:
  provider: azure

  secretObjects:
  - secretName: kv-secret
    type: Opaque
    data:
    - objectName: AZURE_OPENAI_API_KEY
      key: AZURE_OPENAI_API_KEY

    - objectName: DATABASE_URL
      key: DATABASE_URL

    - objectName: JWT_SECRET
      key: JWT_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "c13cfe22-37f2-4013-be0a-3f6fc84346dd"
    keyvaultName: kv-codereview
    tenantId: 1721d0c3-fba6-4501-83b6-4afe93a160bb

    objects: |
      array:
        - |
          objectName: AZUREOPENAPIKEY
          objectType: secret
          objectAlias: AZURE_OPENAI_API_KEY
        - |
          objectName: DATABASEURL
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: JWT
          objectType: secret
          objectAlias: JWT_SECRET
