apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-raptor-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Thanu-sri1/Code-reviewer-AI.git
    targetRevision: main
    path: helm
    helm:
      releaseName: code-raptor-prod
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-codereviewer
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
